export { default as HomeBenefits } from './HomeBenefits.vue'
export { default as HomeCollection } from './HomeCollection.vue'
export { default as HomeFeatured } from './HomeFeatured.vue'
export { default as HomeFeaturedBanner } from './HomeFeaturedBanner.vue'
export { default as HomeHero } from './HomeHero.vue'
